modLoader="javafml"
loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

[[mods]]
modId="addgems"
version="1.1.1-1.15.2"
displayName="Additional Gems"
#logoFile="examplemod.png" #logo file
authors="Advaluti"
credits=""
description='''Additional Gems by Advaluti'''